version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file input.yml --s3-bucket toobrien --output-template-file output.yml
artifacts:
  type: zip
  files:
    - output.yml 
